### ISSUE TITLE
pixie_example() fails with ValueError related to imagecodecs package

### ISSUE THREAD

**Issue by SilverViking** [saeyslab/harpy#42]
When I try to get the data for the pixie example, I run into the error `ValueError: <COMPRESSION.ADOBE_DEFLATE: 8> requires the 'imagecodecs' package`:

```
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sparrow as sp
the value of the environment variable BASIC_DCT_BACKEND is not in ["JAX","SCIPY"]
2024-07-30 14:59:21,778 - sparrow.image.pixel_clustering._clustering - WARNING - 'flowsom' not installed, 'sp.im.flowsom' will not be available.
2024-07-30 14:59:21,982 - sparrow.table.cell_clustering._clustering - WARNING - 'flowsom' not installed, 'sp.tb.flowsom' will not be available.
>>> from sparrow.datasets import pixie_example
>>> from sparrow.table.cell_clustering._utils import _export_to_ark_format as _export_to_ark_format_cells
>>> from sparrow.table.pixel_clustering._cluster_intensity import _export_to_ark_format as _export_to_ark_format_pixels
>>> from sparrow.utils._keys import ClusteringKey
>>> sdata_ark_analysis = pixie_example(["fov0", "fov1"])
Downloading builder script: 100%|█████████████████████████████████████████████████████████| 8.99k/8.99k [00:00<?, ?B/s]
Downloading readme: 100%|█████████████████████████████████████████████████████████████████| 2.82k/2.82k [00:00<?, ?B/s]
Downloading data: 100%|█████████████████████████████████████████████████████████████| 374M/374M [02:03<00:00, 3.03MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████| 16.1M/16.1M [00:04<00:00, 3.24MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████| 1.57M/1.57M [00:00<00:00, 3.33MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████| 1.38G/1.38G [07:01<00:00, 3.29MB/s]
Generating cluster_cells split: 1 examples [00:00, 64.00 examples/s]
Downloading data: 100%|███████████████████████████████████████████████████████████| 9.21M/9.21M [00:05<00:00, 1.76MB/s]
Generating pairwise_spatial_enrichment split: 1 examples [00:00, ? examples/s]
C:\Users\frank\.cache\huggingface\datasets\downloads\extracted\55e8e42d018f9c741abf79cb162efe0362e166713d871196f7e965c5c3df7215\post_clustering
2024-07-30 15:09:29,801 - sparrow.image._manager - WARNING - No dims parameter specified. Assuming order of dimension of provided array is ((c), (z), y, x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\sparrow\datasets\pixie_example.py", line 93, in pixie_example
    sdata = sp.im.add_image_layer(
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\sparrow\image\_image.py", line 216, in add_image_layer
    sdata = manager.add_layer(
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\sparrow\image\_manager.py", line 68, in add_layer
    arr = arr.persist()
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\dask\base.py", line 349, in persist
    (result,) = persist(self, traverse=False, **kwargs)
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\dask\base.py", line 999, in persist
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\dask_image\imread\__init__.py", line 99, in _map_read_frame
    return _read_frame(fn=fn, i=slice(i, j), **kwargs)
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\dask_image\imread\__init__.py", line 104, in _read_frame
    return arrayfunc(imgs[i])
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\slicerator\__init__.py", line 226, in <genexpr>
    return (self._get(i) for i in self.indices)
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\slicerator\__init__.py", line 206, in _get
    return self._ancestor[key]
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\slicerator\__init__.py", line 187, in __getitem__
    return self._get(indices)
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\pims\base_frames.py", line 100, in __getitem__
    return self.get_frame(key)
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\pims\tiff_stack.py", line 131, in get_frame
    data = t.asarray()
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\tifffile\tifffile.py", line 8993, in asarray
    for _ in self.segments(
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\tifffile\tifffile.py", line 8807, in segments
    yield from executor.map(decode, segments)
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\tifffile\tifffile.py", line 8782, in decode
    return func(decode(*args, **decodeargs))  # type: ignore
  File "C:\Users\frank\miniconda3\envs\harpy\lib\site-packages\tifffile\tifffile.py", line 8210, in decode_raise_compression
    raise ValueError(f'{exc}')
ValueError: <COMPRESSION.ADOBE_DEFLATE: 8> requires the 'imagecodecs' package
```

The same issue is also documented here: https://github.com/conda-forge/tifffile-feedstock/issues/115

In my conda environment I also have the incompatible combination of `tifffile` and `imagecodecs` versions described in the issue above:
```
(harpy) C:\git\harpy>pip show imagecodecs
Name: imagecodecs
Version: 2023.1.23
...
(harpy) C:\git\harpy>pip show tifffile
Name: tifffile
Version: 2023.8.12
```

**Comment by ArneDefauw** [comment]
I cannot reproduce this issue on macOS and CentOS. Did you use a fresh install?
```
conda env create -f environment.yml
pip install "git+https://github.com/saeyslab/harpy.git#egg=sparrow[testing]"
```

**Comment by SilverViking** [comment]
I did indeed do a fresh install (following the harpy installation instruction for the case without the plugin).

However, I now tried again and the problem has disappeared.

In this new installation I immediately got more recent `tifffile` (2024.8.10) and `imagecodecs` (2024.6.1) versions than when I logged the issue.

Closing the issue.
